using System;
using System.Collections.Generic;
using System.Linq;

namespace ComputingGCContent
{
    class Program
    {
        static void Main(string[] args)
        {
            //HighestGCContent(">Rosalind_6404CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG>Rosalind_5959" +
            //    "CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC>Rosalind_0808CCACCCTCGTGGTATGGCTAGGCA" +
            //    "TTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT");
            HighestGCContent(">Rosalind_9097" +
"AATAAAAGCCTGTGTCATCACTGATTGTCTTTGACGCATTGCATTATTAATATGTAATTG" +
"GGGGGAAAAGGTAGAAGGACCCTGTTTGGTCTCGTAGTTCCGGACATTACCCCTTGGGTA" +
"TGTCCTTATATAGAGCACAGCCACATTGCCCACGGATTATGACGTCCATACGTGACTGGC" +
"CAAGCGTTGACGATCGAAAATGGCGTTGATCCGTAAGACGCATCCCCAGGAAGAATAAAT" +
"TAGTATTTAATCCACTATCCCTCCTTCTAGGCTGGTATACGCACTCGTTTATTCCTTCCC" +
"AGTGTCGTGCACGAAAGATGAGTTGTGGCACCTTAGGCCAGGGCGACACATAGTGCGTAA" +
"GCACAATCTACTTGCGAACGACAGTGTTGGGGCGATCAACACGTGCCGAGGGCGTAACCG" +
"TATGATAGAGGAACGCGGTACGTATGTATCATCCAGCTGGACTGGGCAGAATTCCCTGCT" +
"CAGCCTAAGGACTTATTTTGTTATATACACAACAACAGCGACAGAGAAGTGCGGGTCATT" +
"CGAGTATGCTTCCTAAGGGTAGTTGACAGGGAATTTCCTAATACGTTGGAGGGGAAGTGT" +
"CGCATGAAAGTAAAGATTACTCAATATAATGTCGCGGGGAAATTTGGTGGGGCACCTCCT" +
"GATTTAGCCATCTGAACACACATTGACTTAATAAACACTACCACGGTTCCCTGGTGTATT" +
"TTCATGATCTACAATCCAGAACAAACGTTCTGAACACCTTCACTATCACAGATCCTGTGG" +
"TCCCCTTAGCCAGGGAATTGCAATGTACCACTTTCTAATTCCATTCTGAATTACATTGCT" +
"CATCCAATTGGACGCTACGCATCGACCGTACTGGGGGTTGGAGTTTATTGCCCTTCTCAT" +
"CAGTATGCTCCCCACCACAAGCACAGTACGCTTCCAGGCGCGGAACCACACGTATCGTA " +
">Rosalind_6461" +
"GACTTAGCAAGCACCGTGGGTCTGTCAACATGTCAGACAGTGGAAGTGTGGTTCGGAAAA" +
"CAATTGTAGCGAAAATACACGTCTCGATCAGGGGCTTCCTCACACTACTTCTCAAGGTTT" +
"CAAACAGTATCATCCATTTTTTCATGAATCCGAGGCCTGGGCCGGGTATTCGACGGCCTA" +
"AGTCGTAGTTAAGAGAACGCGTACTCGTTGTGCGAATGCGTACCGGACGTGTACACTGCC" +
"GTGAAACCCCTACCCATTTGGTCGCTATCCAGTGCGAACGCCGCCGTGGTAACGGCCTCT" +
"ACCTCCAGCAGGAACATCCGCGGTGCTCGAATAATCTGGTACTTACTGTAGACACGGGGA" +
"TGTATGTTACGCCCCGGAGCTATTAGACAGGCAGTCCGTGCATTGCGTCAGTCATCTGGG" +
"TCGCGTACTGCTCACGTCGCGCCTTTCTGTAAATCCGGGCATACATGGATTTCCGCTCCG" +
"GTCCTTTCATTTGCAACAGGCTAACACCTGTTCGAGAACTAGAAGAGCGAGCGTAAGAGT" +
"TTTCCATGTTTGGATGGACTTTAACAATGGCCCCTAGTGTACAGCGCAACTGAGAGTCAA" +
"CAGGTCTGCTACCTTTTCCCAATGTCGTGGCGGTTGACGTCCGTCCCAGCTCGCATTAGA" +
"GTTTGAGTTAGTATGGGATAGATCTTTGTTTTAGCTCCTTTACTGTGCATGGCAGTCCGC" +
"ACATGGCGTCGTGCTCCATGGGCCGCGCCCTGGATTTCCCTCGCCACTCCAACGCCTGAA" +
"GGTAATTTCTCCGCGTTAACGCGTAAATATGAGCCATAGCTGAACAATACCAGTTGGTGT" +
"ACGGAACACGTG" +
">Rosalind_4153" +
"AATGTGTCGGGAGGTGGGTTACAGCGGAGAGCTATCCCATTCCCCCCATGACGCCGCGCG" +
"GTCACCGATTTTCCTCTGGTGCTTACTCGAAGTATTTAAAATGTTGTCGTGTAGTCACGA" +
"TATTGCTTAGACTCTCCTTGTTCGTTATTACAGCGGACAGTGCGAGACCGGTATAGACGT" +
"TGAGCTAGACCCCTCGGCCTTGCAGAGGCGAACTCGCGCGCACACACCATGCCAAGCAGC" +
"ACGCGGTGCTCAAAGGTTGCGATTTAAAGCTAGTGCAACCCGTCCGTTTGCCTGGGTTCA" +
"TAAATAAATTGCAAACCACGAGGCTGGTTTGTTAGATTGCATGAAATAGTGCGGCACTGT" +
"AAAGTGGGTCACTTTTGCTAAGCCTTGCGTCTCTGATCGTTGCCCATTGCGCTAGCTCGT" +
"GTCGCACTCAAATCGTCGTGGGGCCTACTCTGCAAGGGACGCACGAAATTTATAAACCTT" +
"AGTTGTTCTCGCTGTTTAGCGTGCAAGCACCGTCGTGGTCACCTTTGCTATACTGAAAAG" +
"AGATAAGCTGCGTCCCTTAACTCCATCTGACAGACTCGGAAGTGATGTTGGAGCCTAACA" +
"GTAACAACTCCATATTTCGTAATCCACAGTCCGCAGGAAAGGCTACGCAAGCCAATTACT" +
"TGACAAGTACTTTCATAAATATTTCATCGAAAATTCTTGCAGACTGCTAACTTTACTAAC" +
"GAAGCTGCGCGCGTCTTAAGCGTCGCGCAAGTAGTGTAGCGCGGTTCGCATCCCTTAGCG" +
"ATGTCACCAGATGCCGTGCTCTCAGCTGGATGTTTGGAGGTCTGAGACAGTGCGTGTCTT" +
"TTGGCCGTATT" +
">Rosalind_1267" +
"GAGTGACGACTCTGGCGTTCCGTCTTTGACGAGCATCTCGGTTCTAAGGTTGTTTTGTGA" +
"CGGAATATTATTGGGGGGTGCATACCCTATCGGGATGATCGCCGGGCCTTGGTTTGGATA" +
"GCGTCACTCTGACGGTTAAGTGTCATCCTATTTCCAGTGTGTCCATCATAAGTCTGCGCC" +
"GCGATCACTTCGAACGGATAGGTTGATACCTGCCATTATTGAACATTAATCTATGTAAGT" +
"CGTTGTCAGCTAACTTGAACCAGGTTGCTAACACGTTCCGGACCACTTAGTCGAAGGATA" +
"TGAACTGGAGTTAGCTGGTTACCCGCATTCACTCGTCACCGTTTCCATATGAGGCGACGC" +
"GACTGACTGAATTTTAACCCACTTGACGTCGCCGGCGTACGCCAAATTTTCACCTCATCG" +
"GTCAGCCTTTGCAGCGGAGCACGAATTGTCCGGCAGCAGGCCGGGAGGCACAGAAGATAC" +
"GGACACGAAGCTAAACTAATCAGAGACAACGTGCCGTAACTTCTCCTAGAAATTTCGGAT" +
"AATACGGGTACCTAGGCTACAGCCAGCTTGAGCACTATCCGGCGTACACCTATTTGGCGG" +
"CTCAAAAGGCCTATAACATAGTAAAGTGCAGTGGGACAGGCGCCATACAAAGTACTGCAG" +
"GTACCATGCTACGGTGTGAGAACCTCTGTCCTTTAATGTTATCGGTCTTTTCCGGTAGGG" +
"CCCTAAGATTGTATCGGAAGTAGCAACGTTCTACCCTGTCCAGTAGGCACCTCGTCTCTA" +
"CATTCGTTATTAATCTTCGCCTTGTCACACTCCCTCTGGGGTGATAGGGTCTCGTCCCAC" +
"TTCGCGGATCAATCCTGCAGGAACGGTTCAACAAGAGCAAACGCACTCAAAACACGAACT" +
"TTTAACGAAACAGATAGTTTAACTGCCATAATGTCATCTAATGAGCACTCTTACAAAATA" +
"CGC" +
">Rosalind_7370" +
"TCCAAGGGGCACGTATCGTATATTTTTTAGCGCACAGACGCCCTTGCGCGTTGTATCAGC" +
"CTTGAGGTTTGTAACCGCAGCCCTATCTACAAAACCTATGAAACGTAAGACCCCTCTACC" +
"AGGGACAGCGAAGCGCCATTGCATGCGACCTGATTGTCTGGTCGCTTCCATCAACCCTCT" +
"GGCCTTAAAACCTTCTTCTCAGACAGGTCTTAATAAGCAATGGGCGTCGTATGTGACCGT" +
"CTCTCCAAACGTAGATGTGAAGCGCCTTTACACCGGGCGAGTTACATGTTGGCGGGAACA" +
"GTAATCCAATGGGAGCTGATTTAAATGTCTCTGTTGTAATCGGCCGTCTCAGCCTCCCTA" +
"GAATGCGCGCTGCGCCGGTCGATGAGATTGATTACGAAAGTATTCGACGATTAGAGGCAT" +
"TTCGGGACGGATGACTGGCAGACTTTATCTCCGAATAATGAGTCTTTTGCTTCCCGAAAC" +
"GCGCGACTTAGCTGCACTCGGATGCTGCGAGGCCCATAGGATGTGTTCGCTGGAACACAC" +
"TACACTTGCTGCGATCGACTTAAGGGGGCACCAATAAAACCGCCTAGATGCGGTACGCCT" +
"TGTGAATGGCGCATCGTGTTTGCGCAGTAGTCGGCGTCTCTGTTCGGACAGGGCATGAGA" +
"AGGGTATTGACGTCCCAATCTCTGGTTGCTAAGGTCAGATTCTTGTTGTTGCATAGCAGC" +
"TTTACCGTACATTTCCATAGTATTTCGATATGTCGGCTTATCGGGACGTGTATCCCACAA" +
"TTCAATTTCTAGGTGGGCTTTCAGCGGACTATGCATCTAAGCTGTGTGTCGAGGGTAAGA" +
"TCATATCTGCCCTGCATCTTGGGGAAGTTGATTATTCGACGTTGGACCCCAGTTTATTCG" +
"CAACCCCAGGCATTCGAAATTCCAGACCTAGAATTGCTGAGTCCTCGCTAAGGATAC   " +
">Rosalind_2520" +
"GGGACGAAAATAGGTTTCCTTAATCTCTCAATATGTAGTGTTTTGTAGGTTCGGCCTTTT" +
"CGTGTCCACGAACCTTCGAGGTTATATGCCATAACCTCGCCGCTTGGTGGTTCCGCCCTG" +
"TGCGGCTCTTTGAATTACTGATGCATACAACGATTCTGTACGGGTGTTTTCCACTGTCAA" +
"CGAATAACAGACCAGACACGCTTGGACGAACGGCTGCGCTTTCGAGACTAGCTAAGCATC" +
"GAGACCCATGTTAGCCGCACAAGCCCCTCTAGGTGTATTGTGGACCACCTGGCGACCTTA" +
"CAAATCTGCTCGTCCGGGTCCCGGCCTGGTCCCGACAGATGCCCACGACGTGCTTACTCC" +
"TCTTACGCTAGGGGGATTACCCAGACACCCAGAGAACTCTTCAACCTTCTGAAACTGCCG" +
"TATCGCTGGCTCAATCGATCACGATTTCGAGCATGTGCAGCAGATCCGAGTAGCTTTGAT" +
"AACAGGCTTGTAACAGGGCGAAAGCGGCTACGTTTCATTGGCAGCGAATGATAAGAACGT" +
"TTCCATAGTCCTCAGCCTTGTATGACATTTTCACATCCACACGAGACAGCACGAGTAATT" +
"CTTAGCCCGGGTAGAGATCAGTCTCTTGGGACGCTGTCGTCCGAGGGTATCTTCCCTGGA" +
"CGTCGAACCCATTAGACGAAGCTATCGTTTCAGAGGAAGACGATAGTGCCGCCAGTTAAT" +
"GCTTTTCGCCCGAGGCGCTGGTATTCAGAATCATCCCCGGTCTTTTGTTAGAGGATACCT" +
"TATGCGTTATCATTCCATGCATTGGCCCA" +
">Rosalind_7400" +
"CTGTTCTTTGCACCCTTGCGGTTTATACCTTCAGCCGTGGAAGGGTTACAGAACTAAACA" +
"GATTTGGTGTGGTAACCCCCATCGGGAGAGCGCGCACAGCGCGAAAACCGCTGCCATTGC" +
"GCAGCTGATCCCATAGGGACGATAGTTACGTTCGTCTCAGCGTTTTCTGGCCTGTAGCTT" +
"CACTACAAACACCTTCGTAAGATGACATGCAACAATACTACTCACAGTCTATAGACGCTT" +
"TCCTGAGGCCACCTTACAAGGTTGGGGGTATGTCGAGATTTTTTGAACATTTTGATAGGG" +
"CGACTGAGGAAGAAAGTGAGCTGTTTCGCATTGTCAACGGCCTCGGTACAACCCACCTTA" +
"TCGTGATGCCGTTATGAACTATTCACCAGATTCCAGCCTGGCACGTGCACGTCGTAGCGT" +
"TACCTTGTGGCCGTATGGGCCGACAGTAATAATTCTTGCGTAGATAACTTGTTACTCTTA" +
"GATCGAATTAATGTTGGATGACGTTTCGTTACTCCCTGAGCTGCGTAACGTGTTAGGAAC" +
"GCTATGACATTCCCCTACTGTCGTAAGCCGCGTTGGCCATAATTCTCAATCCTCCAAACG" +
"CCTTATCGCGGCAATCCAAACCCTGTATACACGACATGGGCACATATGCCAGTAACTAAA" +
"GACATCCCGGATAAATCTACGACCTTAATTCTTATCGTCGCTGCAGAACGAAGATCATTT" +
"CCGGATTGATGGGCGAGGCCTTAATTAGAGCAAGCCGGGAAATTCCATGCTACTCGAAAG" +
"TCTTTAGATGCGCGGAAACGCTATAAATGCAGATCCAGCATGGAGGCATGCCCAGAAGTA" +
"CCTTGTCACGACCCGTAGGTTGAGCATC" +
">Rosalind_5558" +
"TCCTAGCCGTTTGTGGCACCGCCAGCGGTTGTCCTCAATCGGTGCAACTTGTAATCGATT" +
"TTCATGCACATACTCGGGAAAGCAACGTCACTCTACAGTAGGGTATCTGACCAAAATTCC" +
"ACCCACTGCACTAGAATGGTTCTAGTACGTTATGAGCAGAAGAAAGAGCGCTTGAATTGA" +
"GGATCGTAGCTGCTAACTCTTAACAACGTACGTGTGTTGGGGTAGCGAGTTACTAAGGAA" +
"AGGCTTGTCCCTAACTCTTGGTATTCGCTAGTGGCCCAAATCTATGTCACGCGAACTACA" +
"ATCAGTCGCCGCTCCCCGACCATGCTATGTGCTATGACCGATTTCTCTATATGGCAAAAT" +
"TATGATTGAGGGTTTGCGTGTCGTTCTCGGACAACACGGGACATTGGTGGCCCGTACATG" +
"CTCTTAGGCAGTAGGCAGTCTTAGGTGAACGGCGTTGAAACGACCCTGGGGGTTGTGCTA" +
"TACCACATATTCGACTTTTTACTAAGTTAACGGGAAGCGGCTAGACCGCTTCTTTTTCTT" +
"TGCAATAGGCAGTATCTTGCTGTATGCATACATTCCGTGTCGTATGTCACTGGTGTTCGG" +
"ATGCACGTATGACCTACCACCGAACTCAATACTTCAATTCTACCTCTCGTCTCACGTCCT" +
"TGATAACAAGAAACTTGCCGAGAGGCTTGTATAATGTGGAGTAATCAAATACAGAGAATG" +
"TTCAACGTCCTTTTTTATCGTCCCTGGGTCAAGGCCGGTGCGTTTCGCAAGACCGATTCA" +
"ACCTTTCATAGGCATCGTAAGTTTCAGGAAGGAA");
        }

        private static void HighestGCContent(string DNA)
        {
            //input: DNA strings (in one string variable) in FASTA format, which means each DNA string is preceeded by >Rosalind_XXXX
            //output: the ID of the highest GC content string and the GC content percentage
            //GC content is defined as the percentage of Gs and Cs there are in the string
            //get the data ready to process. We need to only process the DNA characters, however the string has an ID in the beginning
            //However we still need the ID and the DNA connected so we can return both at the end
            List<string> dnaStrings = DNA.Split('>').ToList();
            double answer = 0;
            double highestGcContent = 0;
            int highestGcIndex = 0;
            //once the data is ready to process, go through each character and add up all the Gs and Cs
            for (int dnaString = 1; dnaString < dnaStrings.Count; dnaString++)
            {
                foreach (char character in dnaStrings[dnaString])
                {
                    if (character == 'G' || character == 'C')
                    {
                        answer++;
                    }
                }
                //Given the total of Gs and Cs, find the percentage of those occurances in the whole string
                double gcContent = answer / (dnaStrings[dnaString].Length - 13) * 100;
                if (gcContent > highestGcContent)
                {
                    highestGcContent = gcContent;
                    highestGcIndex = dnaString;
                }
                dnaStrings[dnaString] += $"{Environment.NewLine}{gcContent}";
                answer = 0;
            }
            //Now that we know all GC content of all the strings, find the highest GC content
            //Return the ID of the highest GC content string (Rosalind_XXXX with NO <) and the GC content on the next line
            Console.WriteLine(dnaStrings[highestGcIndex].Remove(13) + Environment.NewLine + Math.Round(highestGcContent, 6));
        }
    }

}
