using System;
using System.Collections.Generic;

namespace TranslatingRNAToProtein
{
    class Program
    {
        static void Main(string[] args)
        {
            RnaToProtein("AUGCUGGAGUCUCCCAGCGAGUGUUUCAUCAUGAUGGCCCUCGAUCAGGUGGCCGACGUGAUAUUAACUCAAUUUGAAUUCAUGGAGCCGGUGGUUCAGUUUUUACUGUUCCCGACCAAGGAUACAUGGCUGGCCCCCUCGUCGGCCCACGGCCCACGACUGUGUCGAGACCAGGUCCAAGGUAACUGUUUUAUUCCAUCCGAUGAGGCUAAGAAAGUUUGUUUAUACCCAUUUAUCGUUGGAUCUCAAACUUCAGCGAGAAUGCCAGUAAAUGUUCCUCGUCCUGGCAACGUGGGUUUAUACUGGCCAACUCCUCUUUCGCCUUACGGAGCACGGUAUCCUCUUUCCCAGCCUGGAUUGAUAAACAUGGCGGCAGUGCGUACAGUCAGCUGCUCUCUUGAUGCCACAUUAUUGGUACAUCAGGUCCAACGCCGCGUAUUUAAGCGUGCGGCAGGUAAGAAUUGGCCGCAGCCCAGCACUCUAUGGCCGUCACGUAACUUAGUACGAUAUUAUACCCACCGAGACUUGAUGAACCACCAGGAUGAGACUGACUCCCAUAUGAUUCAUAAACGUUUCGACUUCGAGCCUAGGAGAGGUAGGACCGGCAGUUCACUUGCCGCUGCAAUUGCCGGGCCUCGAGUUCGCCAUAUCCCGAACUGUUUCCUGCUCUUAUACAGCAUCCAGGCAGUGCACCAGACCUUCCAGAGGGCCCGUUACGGUUGUACUUCAAAAGAGGAAGAAGCGUUUAUGAUGCCUCAUGGACCAUUUCCCAAAUGCAGGGGUUUUAGUGAGGGACACGCCAGCGGGCAGCCCCAUCGAUCUCAGCUCCAAGCCCCCGUUCGGUGGAUCCAUAUCUAUAUCGAAAACUUCGGAGCCACGAAUGGCCAGAUGCGCUUAUUCGUCCAGCUUAAAAACUGUUUACUACGUAUAAAUAACGACUGCGUUAGCAGGUUCCAGGAAUUUUACGCGCGGCAGUACCGCGCCGCUGCGUCUGCAGGGUACGGAACUAGCACCUCACAUCGGAGAAGUCAGAUCACCAGGUUGCAUCCAAUGCUAAUGUUUGAUGGAAAUGAAGGCUUUCCGUGGUCUUUGUUGAUACCACUACGCUUCUGGACUAUCCGAACAUACGUCAGACAAUAUCGCGCCCCGUCCCAAUCUGUACUGUUGUUCCACGUGCGAACAAGAGCUUGGCAACCGAUAAGCCUGAGAAUGCCCCGGUGUAAAAGGCCCCCAGCCUUUCACGCGUUUAACAACCUAUCAAAGGGUUGUCACAACACGUUGAUCUUACUUGGCAGAGUGAUUCCCCGCACGAUUACCUUUACGACGUGUCCGUCGUGCCGUUCCAAGGCGACUCGAUUCAAGGGUAUAGAAAUGAACUCACUUCUAUCAGAGAGUCCUAUCGCCCAAGUAAUCAAUCCGUAUUCACUAGUAAAGCAGUCACCCAAUAGCAGCUGCAUGCCUACUAGGCGAUCAGCUAGACUCGGCCACAUGUCGGAGGCCGUCACCGUCUGUUUAUACGCAGUCACCAAUGGUGCACUCCGGUCUCGUUAUUGGCGUCCGCUGCUUCUCUUUGCAGGGAUUCGGGGGUGUCUUAGUGCCUGUGCCUCCACCGCACACAAGGCGGGUCACGGGGCUUCCUGUCAAAGUGCGUCACGAUAUCCCGGUGCGAGGGCACCUCCGGGGCAUGAACGGUAUUCCUCCACGGAUGGCGGAGCAGUCUCACCUACAGACCAGACAGUCUGUAGGUUAAGCCGCGUGACUUUUAGAGAUCAGGACGGUAAUAUUGAUUACUAUAGGAUGCCGGGGCGGGGAUAUGCAGCGUGUAGGAGUCUAAAUGUUCGCCAGGGCGUGCCUGCAGUAAUCCCUGCGGUCGUCUUAUCGACGAAUAAGGCUCACUCUUGUCAAACCGCCAGGCCCGGUCAUAAAGGAGUGCCCGCAUCACGGCGCAAUGCCGCCCAUGAGGGAGUACACUUGCUAGUUCAGCCGCCUCAGGUGCAAAACGCGACUGGGCAAUAUGUAUGCCCGGACUGUUACUAUCGCCUACGUGCAAAGAGUGCACUGACGCUAAUAUCAACACCAGUCGGCAAUUCCCCGCGGCGUACAUGUGGUGUUGUGGAGGCGUUUCAGGUCCUCGGUAUUCUGAGGCUGCCACCUUCCGCGUCGGCUGUAUCCCCAAACGACCCAGACAACGCGAGUGUAGCAUGGUCUAAUAUUCAUACGCCACGCAAUCGCUUCCGGGACGUUCUAUUAUCAUUACCUCGGCAAGAAACAAUUGAUGCACACUUUCCAUCACGAAUUUAUGGAGUUCGGCGGACGAGUUUUUAUGAUCAUACCACAUCACGAGUGUUGAAAUUCCCAGCGUUCGUUGACUGCUGGCUAGGAUCAACAGCCGUGCGCAUCGUUUGGUCGUUAACCGCGGCAUUCUCAUCGGUAAGAACGCGCGAACGUUGCGGAGCGUCUUGGUACCCCAAGGUAAAGGACAUUGUCACGGCCCCAGGGAUACCUCUGGCUGCGGAUGAUGCACGCUUCCGCCGUGAUGUUAGUCCGGUCUUGCCCGGUUGGACAAACGACUCGGCAGCGCCCGAGUUACUACGCGUUCGGCGCCUUCGUAGUCCAAUCGAGCGCGGGAGCCUAAUUGCCCUUCCAAAUAGGAUAGAAAUAUUUACUAUAGCAAUCUAUGGCUCGUCUAACGUAGAAACUAAUAGAUUGAUGCUCUGUAGGCGGGUCAGGGCCCAAUCUGAGCAACAAACUGGACUCGCCUGGGUUGAUGUGGCGUUAAGAACCUUUCGGUGUGUUCGGGACUCUAGACCCAACAACCUAAGGUGGGCCGGUCAGACGCGUAAGAACUACUUAUACUAUUUAGGCCCGCGGAUGCUAGUCAGGAUUCAUCGAUGCCUCCCACAUUCUCCACGUACGGAGGGCAAAUCGAUCUUAGGAAUUACUAGCGCCUUCUGGACUGUAUUACGUUAUCCUGCCUAUGUAUCUCCUACUGGGGGUAGAGGGAGCAGUACGGGAACAGGGACGCACAGCAGGCACUCGGAUCAUUCCUUUUUUUUCUGCUCGACUCCGAUCUUCCGUAGCUUGAGCAAUCCCCCUCCAUCUGUUGGUACGUCAUGCGCACUCUUGAUGUCCCAAGCAAGCAUACGGCGACAACAAAACAACCACGUAUGCCAGUCACUUUCCGAAUCCGGGGCUAUCAUCACGAGAGAUUUUUUUGUAGCACGGUCGUUCAAGGCCGCUCGUGGUGCGAACCAACUCAUUUCUCAAGUUGGGCUAAUAAGUAACUCCUUGGGGCCUUGGGAACAACGAUGUGUAUACCCCGACACCGUGGGUGCUCUUGGUACUGUCGAUUUUUGGACCGGGGUACGAUGCAUUAGCAUAGGUCCGUCUGCAAUGAACCGGCAAGUCCAAGCUCCAACUAAACCGGCACUUAACCAGAAGGUUCAUCUGUUAAUGGAGCAUGUGGAAAGACGAUACGGGAGAUUAACCCCCCCGCAUCCCAAUUGCCGUCCUGGGUAUAGACCGGUGAAUAUAAGGGGCGUUUCGAUUAACGUUGGUCCAGAGACUAAAGCCGCCCGGUUCUCCAAUAAACCCGCUGUUAGGCGCCAUGAACCCGUCGGCUUCGAUUAUGAAGGCCGAAUGUUUAUUACUGCGCUUAUGACAGCUCCUUAUACGCCUAACAUUAGACUUAUGGCAAUAACUAUAACGUUCCCGGUGAUAUUUGAUCGUAUAGCACAUAUUAUAGCAGUCUCUAAAGCCUUACAUGCAUCGGCGCAACUACACCCGGCCUCGCAGUGGAUUGUUUCUGGCCCUACGUCUUACCUUAAGCAAUCUACAACGGCAUCAGAAGGACCGCUUCUCUUAAGCGGAUCUUACCGUGUUGAACAAAUAGAACCGCAUCAAUUUGUGUUAGGCAGCAUCCAACUGGGUACUUCAGCUGAUGUGUGUCUAUUAGGCAGGAAGUGUUAUACAAAUAAAAACCGCUACGAAAGCUCACUAAGGAAGCAGAUGUCCGACUGUGACGCUGUGCGCUUCCAGGCCUUAUCCUACCGCCACGACCACUCUACAGAAACCCGCCAGCUCAUUCGAACGUUAAACUCUAAGGACAUCCCUUCUUUGAAGGAGCACCAAUUGCUUCUUUACAGGCAGCAAGCAAGCUCGUCGGUCCAUCAGUUCACUUCCAUUGUGCGCAUUCGGUGUGGUAGCCGCCUACACCACGAGGGGAAGAGCCGUCCCCAAACGGGCUUAUCCCAGUUCGACUAUCAUGAAGUAGGCCGUUGUAGAGACGGAGAUCAGAGCAAUUACAGAGCAUUUCUCCCUUCUGGCGGGCAUCACAUUUGCCCUUUGCAGGUAACGCCAGUCGGUCAUGUGAAUCUAUGCAUUUGCGGAUAUCUUCCAGCUCAUACAAAUUCUUAUGUACAUUAUGCGGUCCCCUCCUUACACCAAUCAGAGCUAAUGCACUCUAGUGUAAUAACUAUUAGACACGAUAGGGUCGGUACGGCGGAGUUACCUCUAUGCCUGCUGAGUACCAACUCUGCUGCCAUGAGCCGUUUUUAUCGCACAGCUAAUGCGAUGGUUGGCAUUUUGCACCGUACACCUUCUCUCUCUAUUAAUGAGGUCGAGACCACCAUCGAUGCCGAAGUGCUCGGGAAUCAACUGGCUUAUCAAAUUCAUUCACGAGAUUACCGGCGACCGCGCCGCGUAGUCAAGGAAAAAAGAGGGGAGACUGGCUUCUGGGUAACAAAUACACCAUCGAGACAAUCGGCUCAGAGAUUCCGACUCGCACCCUUAUAUGCAGAAGGUCUGCAGUUGAGGACCCUCUAUCUUAGCAACUCACCCGUUCGGCCUUCAAUACUAUCAUGGUAUCAAUUGGAUAGUCACAAAGGUCGGACAGUUUUUGUGGUGUAUACAGGUUGUUCGGACGAUCCACAGGAGGGCUGGAACUCGGGCGCACAAUGCUGCGAAAAGCCAAUAAGAGAAGAAAGCUUUUAUCGGAUAUCGUGUGUGUGCUGUAGACAUACCCACUCACGGACCGUGCUUUCAGGCAUGUCUGUCAACGAAUUUAUCGUGCCCAAUCGAGGUGUGCAUGUUCCGGCUGCAAUGCUAAGGGUCCGCAGCAGGCCCGACAUACUCACGAAGGGCGAGUCUCAGCUCGUCCUGAGCCGUGCAGUAUUUCUACUCGCUAACUUCGGUCACCACGGAUCCUGUGAUAGCCUUACCGAAUCCGAAAACGAUGCGUGGAUGAUGCAAGUCGGGGAAUCGUGUUCGAUGCACUUUUUUACAGCAGCUGAUUCUAGACCUUGUAUCAGUCUUGCCGCAGUGUCAAGUACAAGAGGCGGCCCUCCUGAUUAUUCCUCUGCCAACGCCAUUUGGCGCACAGGAGCACCGGGUACGCAACCUCGUAGUGGUAACAGGACGCUCAACAAAACCAGUUACGAGACGGAACGCGAUUCCCUUCUAAGUCUAUCGGCGGCGAAGUUUGCGUGGUUAGAUGACAAGGGUUCUGUUAUAAAAGUCACGUGCGGCCGUAGGCGUCGGUUCUUUUCACAAGCGAAUCUGGCGCUCGUUGCUUUCCCACAAGGUGGUCUCGGGCUUCUUAGGUCUUGCCGUCCGUCCACCUGUAUAAUCGCCAUUGAAACACAUCUCAUAGAAUACCAGAAAUCACGAGUUGGGGAUACGCGCAAUUCAUACGAACCUAAAUAUUUCACCCUGCGAGUCCACUCCGUAUGGUGCUGGCUAGGAAAACAUUCAAGAGAAACAAACUAUCUCGCCACUGACUCGAAAGGCCGGGCGCCUAUCACUCCGUUGGGGAUACGAUGGGGCUUCGCGCCCUCCAUAAGAGUCUUGACCUUUUCAAUAAACGCAGUAUUGUGGCUUCUCCGCUCGCCUGGACAGACGACGUACAUGCCGCCGCACUUUGCGAACCUGAUUUCGCUUACCACGGGAGGCGUCGACGAGUAUUAUAUUACGCACGGCGCCACUCCAACUACACAAAGAACGCCGAUACAUAACACCGGUGUACUCCAGCUCGGUGGACUAGCGGCUGGUCCUUGGCCGUCAAAUUCUUUAGGCCCUCUAUCUGUACCUUCGCAUGUCCGCCUCGAUCCGAUGCCGCAAGCGUGGACAAAUCGGGUGUCGGCCGUGAGAUCUCGCGGAGCACCUCUGUUUGGAUCGUCACACUUCUGGACUGCGCGGUGGUGGAAACAGCAAUUGUACAUUGGUGAGCUUUUGGCAGUGGCUCCCGCCGUCUAUAGCCAUUCAGCUCCCUGCGUAUCCAGUCGGUGCUGUAGAGCGGUACGUCAGUGCAAGUGGAGCCCUAAGAAACGGGUGUCCCACAGCAGAAAAAAACCAAACGAUUCCUUGAGAAUUCGUUCCACCCCCGUCUGUCGAGAGGAAUGGGUCGGUUCAUUUAUUAACGCAACGCACAGAUUGACGCCAUGGAAACGUAUGCCGGAACGGCUCUAUCUUACAGCUAUGGAACACUGGUACCGAUGCCCACCUCUCUCUACCCUUCGAGGUUGGUCCGUGGGGACUAACUCUGUCCAUGGGUGUCACGCAGGACAUACGACAAGUGUAACAAUUCGGCAUCUUCUCAUGAAAAUGCACAUGGAUUUGCAUUGGGUCGAGUAUUAUCAAGCGGCUCCCGACAAUAUAUCACUGCAGCUCACGUCGGACAUGCUGUGGUCAGACAAAACAUCCAGCACUCCUGCCCUUUUUCAACUCAUACUGUUCAGCUCUUCAGGUAUAAAUACAGCGCUCCAUCAGACCCAUACUACGGCAAGCGUCAUCUUCGAGCGGGACGCCGACACGAGGCGUGUUUGCGGUACUGCUUUAUCGAACCUCGUCCCGGAUAUUACUGAGAAUGAACAAAUAGCCACACCCCUCAGGACAUCGGCUUUAAGCUCCCAGCACCCCCCGCUUUGCUAUGAAAGUCAGCGACUGUCUACAUUCGUGCGGACGCCCAUAGUGCCCAGCGCAUGGGAGUCCCAUAGCGUCAGCCGAUGUAGGGCGCAAAAUAUGGAAGUACAAAACCUCGAUCAGACAAUUACAGAUGUUGUGCCCGAAGGCCAUGCGCGGGGCCCAAAAUUAAUGUUGUUAACUGAGCCCAUUCAUUGGAACAGAUCGAUGCUCUUUUUUAAGAAUAUGGCGCCAUUCGCCUCGUAUCAAUACAUAGGCGCAGAUCAUAGUUGGUUAUCAAAACGGCCUGUCAAGCACAUCCACCAUCUGUCACACAUGUUGGUUAAGCUGCGGGGAUGGUCAAACCACAAUAGCCCCGCGAGUUGUGGCAUCGCUCUACAAACGGAAUCUCGCCACCACUGUGGCGCUGUGUCUGUCUUUAUCAGUCCAAAUGACGCGGAACAAUCGAACCCAGCGAACUUACAGAGCGUACCAACAUGCAUAGGUCGAACCACGUCGACUGAGCAGCGAACCGUCAACCAUGCGUUGGUUGUGAAAGACACGGUGGCCGUUGGUAGUACCUCAGGGAUUCGAAGAAGACAUGGGAACCAUCUGCCGAACCCAGGCCCAUUUGCCCCACGCAAGUCAUCGCUAGGCACGCGUAAAGCACUCCCUGCAGAAGGCUUCAGAGUUGCGGCGGCCGUCGGGCGUUGGACAGAAGAAAUGGGAUGGGACAGUAGCGAAGAUCACGUCGAUUUCGCCCUUCUCCGGGCGUGUCAACUCCACCGUGUCUACGUCGGCUCUACGUCUCUAACCAAAGGCUUCUGUGAUAAGAUUAAAUUUUGUUUACGUUACAAGGACAAACUGGCAAACCCACGCCUGGCCCAACCUGCGUCUGUAUUUAGGCUGGGACAAAAAGUUCGCCUUACAGUAGGUCGGACGUGUGUAGCACGAGUACCAGUAUUUCUCGAGGUCAUCGUGUGCCUCGGCGCCCGGAUCAGCAGUGAAAACGUCGGCGGUCAGACUCUCAUCAAGGCGACUGUCGACCACGACUUGCGUGUCAAGAAACAAAGCGAGCACCCGCGUGGAAACCGCAUGGCAAUGGCCCUAAUUUACCGGAGACUGGUCGCGGUUUGCUUUAUCUUCCGCCUGUGUCAACAUUCUUGGCUUCUCGCGAGAGAACGAAAUACGGCGGUGCGGACGUCAGCUAGUUCUAUCGACCCUAUGGCAUUAUUAUGCAGUACGUUGUAUGGUGUCUCACGCUAUUUAUUUCGUCGUACCUACGGCGACUCGUGGAUCCAUACUCGAAAGGACGCUCAAGGGCAAAGAAUGGCUCACAUAGUUGGGUCUGACGAGCGGCGCAACACGAUAGAGCGAGCCGUUCUACUGUGUUGUUGCCGCACAUCUUUCACAUCGGUCAUUGAGCAGGAUAUUGCUGACACAGGAUACCAUUCGUUCAAGCACUGGGGGACUUCGGCGGUGACCUGGGAAUUUAUAGCCGAGAGUCUGGUCGGAGUUCAUAAGCUGGUAGGGGGUUGGACUGUGCAACCAACUCGUUUAGCGAAUUUUCAAAGCCCUCCUGUGUGGGAGGUCGUGUCCGAGGGGAGAGCCCGUCACGCUGCGCCUCAUAUUUCUCGCUUCUGUGGCCUGGUGACGCACCUGCCCAUACUUUAUUAUGCUUCAGAUGAUUUUUAUCAGAGCGCCCGCGGGACAUCUCUAUUGGGAUUUGCGCAUCUGAAAACGGACCAAUGGGUGGAGCUCAGAGACUCUUCUCUCAAUGUGCUUGGAGGCGUGAUUCGUCAGGAAGUUAGUUCUAUACAGAUCUCUCUCCGUGCGAUCCGGACGCGGAAAACAUUGUGCGCUAACAAGCUCUUAUUCACUGACUUUAUAACUAAGGUAUGCAAGCAGCACCCAGGUACAAAAACUUUGUUAUCGAAAGGUGCUGUCAUGAAUGUAGGAGUUUCUAAUUUCCUACAUGUGGAGCCACACUAUAAUGAUGGAUCUAAUGGCAACCGAUCAGCUUGGCUACACUUGGCCGAAUUCGUACAGAGAUACUCUCGAAAUCGCACUCAUCAAGGCGUACCUACUGUGUCGCAUCAUGGGAGUUACCCUCCCUUUAGCCCUCUCAAUUCGUUCGCAUCUCUAGGUUUGCAGAACCUGUUCAAGACAGCUCAAUAUCAUCUGUGUAAUACAUGCAGCGUAAUAAAGAAAACCUACCGGCGGACCUCUCCAUCACACGUGUGUCGAGCUAUCACGGGGAGCGUGGAUAGAGGCUUCGGGUCGGCCCUAAGGACCCAAUGGCUUAAAUCGAACUACCGGGUAACUUCGGAGUUCUGGUACCGAGGUAACCAUUACUCUAAGUCACACAGAGGUUCGAACCCAAUUCGCGAACCACACCACGGAAACCGAUGCUGCGCAAAAGAUAAUUGGCAAUAUGUAAAGCUACGCAGAGCGUACUUGAACACAGGCUCUCACAGUUUCGACCCGAUGAAUACAACUGACGGGGGUCGAGGGACCGGCGCAAGAUGUUCUUUUUAUAUGGAAUUCGUUGAAUGGCAAAACGAGUCGCGUCCCAGCAUGGAAUCUAAUUACGCAAAGCUGAAUUACUAUCAUAAGCAGCACAAGACGAACUUUUGUUCCUCAGCCUCUGGUUUGAGCCUAUCCAAGCUUAACAUCCUGGGCUUUCCAACCGCCCACGAUCAGAGGUCUCUCUGCGGAUGCCGAAACAGAUAUAUAUCCAAGAUCGGCUAG");
        }

        private static void RnaToProtein(string s)
        {
            string protein = "";
            Dictionary<string, char> rnaCodonTable = CreateDictionary();
            for (int rna = 0; rna < s.Length - 2; rna += 3)
            {
                string rnaStrand = s.Substring(rna, 3);
                if (rnaCodonTable.ContainsKey(rnaStrand))
                    protein += rnaCodonTable[rnaStrand];
                else
                    break;
            }
            Console.WriteLine(protein);
        }

        private static Dictionary<string, char> CreateDictionary()
        {
            return new Dictionary<string, char>()
            {
                {"UUU", 'F'},
                {"CUU", 'L'},
                {"AUU", 'I'},
                {"GUU", 'V'},
                {"UUC", 'F'},
                {"CUC", 'L'},
                {"AUC", 'I'},
                {"GUC", 'V'},
                {"UUA", 'L'},
                {"CUA", 'L'},
                {"AUA", 'I'},
                {"GUA", 'V'},
                {"UUG", 'L'},
                {"CUG", 'L'},
                {"AUG", 'M'},
                {"GUG", 'V'},
                {"UCU", 'S'},
                {"CCU", 'P'},
                {"ACU", 'T'},
                {"GCU", 'A'},
                {"UCC", 'S'},
                {"CCC", 'P'},
                {"ACC", 'T'},
                {"GCC", 'A'},
                {"UCA", 'S'},
                {"CCA", 'P'},
                {"ACA", 'T'},
                {"GCA", 'A'},
                {"UCG", 'S'},
                {"CCG", 'P'},
                {"ACG", 'T'},
                {"GCG", 'A'},
                {"UAU", 'Y'},
                {"CAU", 'H'},
                {"AAU", 'N'},
                {"GAU", 'D'},
                {"UAC", 'Y'},
                {"CAC", 'H'},
                {"AAC", 'N'},
                {"GAC", 'D'},
                {"CAA", 'Q'},
                {"AAA", 'K'},
                {"GAA", 'E'},
                {"CAG", 'Q'},
                {"AAG", 'K'},
                {"GAG", 'E'},
                {"UGU", 'C'},
                {"CGU", 'R'},
                {"AGU", 'S'},
                {"GGU", 'G'},
                {"UGC", 'C'},
                {"CGC", 'R'},
                {"AGC", 'S'},
                {"GGC", 'G'},
                {"CGA", 'R'},
                {"AGA", 'R'},
                {"GGA", 'G'},
                {"UGG", 'W'},
                {"CGG", 'R'},
                {"AGG", 'R'},
                {"GGG", 'G'}
            };
        }
    }
}
